vpc_cidr                = "10.0.0.0/16"
public_subnet_1_cidr    = "10.0.0.0/24"
public_subnet_2_cidr    = "10.0.1.0/24"
availability_zone_1     = "us-east-1a"
availability_zone_2     = "us-east-1b"
instance_type           = "t2.micro"
env                     = "dev"
ami_id                  = "ami-0c1fe732b5494dc14"
region                  = "us-east-1"
#------- Rds---------
rds_instance_class      = "db.m5.large"
rds_db_name             = "mydb"
rds_db_user             = "admin"
rds_db_password         = "password123"
