variable "public_subnet_1_id" {}
variable "public_subnet_2_id" {}
variable "instance_class" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "env" {}
variable "vpc_id" {}
variable "security_group_id" {}